
    create table nasabah (
        tanggal_lahir date,
        approved_at timestamp(6),
        cif varchar(8) not null unique,
        created_at timestamp(6),
        id bigint generated by default as identity,
        nik varchar(16) not null,
        status varchar(20) not null check (status in ('INACTIVE','ACTIVE','REJECTED')),
        alamat_domisili varchar(35),
        alamat_identitas varchar(35),
        nama_sesuai_identitas varchar(200) not null,
        agama varchar(255),
        approval_notes text,
        approved_by varchar(255),
        created_by varchar(255),
        email varchar(255),
        jabatan varchar(255),
        jenis_kelamin varchar(255),
        kecamatan_domisili varchar(255),
        kecamatan_identitas varchar(255),
        kelurahan_domisili varchar(255),
        kelurahan_identitas varchar(255),
        kode_pos_domisili varchar(255),
        kode_pos_identitas varchar(255),
        kota_domisili varchar(255),
        kota_identitas varchar(255),
        nama_ibu_kandung varchar(255),
        nama_perusahaan varchar(255),
        negara varchar(255),
        no_hp varchar(255),
        pekerjaan varchar(255),
        penduduk varchar(255),
        penghasilan_per_bulan varchar(255),
        provinsi_domisili varchar(255),
        provinsi_identitas varchar(255),
        rejection_reason text,
        rt_domisili varchar(255),
        rt_identitas varchar(255),
        rw_domisili varchar(255),
        rw_identitas varchar(255),
        status_pernikahan varchar(255),
        tempat_lahir varchar(255),
        primary key (id)
    );

    create table postal_code (
        id bigint generated by default as identity,
        kode_pos varchar(10) not null,
        kecamatan varchar(200) not null,
        kelurahan varchar(200) not null,
        kota varchar(200) not null,
        provinsi varchar(200) not null,
        primary key (id)
    );

    create table produk_tabungan (
        aktif boolean not null,
        setoran_awal_minimum numeric(38,2),
        id bigint generated by default as identity,
        kode_produk varchar(20) not null unique,
        jenis_akad varchar(50),
        nama_produk varchar(150) not null,
        deskripsi_singkat varchar(255),
        primary key (id)
    );

    create table rekening (
        nominal_setoran_awal numeric(38,2),
        saldo numeric(38,2) not null,
        status_active boolean,
        tanggal_pembukaan date,
        cif_nasabah varchar(8),
        created_at timestamp(6),
        id bigint generated by default as identity,
        nasabah_id bigint,
        nik varchar(16),
        nomor_telepon varchar(50),
        nama_nasabah varchar(200),
        alamat_domisili varchar(255),
        cabang_pembukaan varchar(255),
        email varchar(255),
        nomor_rekening varchar(255) not null unique,
        petugas_cs varchar(255),
        produk varchar(255),
        tujuan_pembukaan varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(100) not null unique,
        primary key (id)
    );

    create table transaksi (
        jumlah numeric(38,2) not null,
        saldo_sebelum numeric(38,2) not null,
        saldo_sesudah numeric(38,2) not null,
        processed_at timestamp(6) not null,
        rekening_id bigint not null,
        group_id uuid not null,
        id uuid not null,
        no_referensi varchar(100),
        processed_by varchar(200) not null,
        keterangan varchar(500) not null,
        channel varchar(255) not null,
        cif_nasabah varchar(255),
        nama_rekening varchar(255) not null,
        nomor_rekening varchar(255) not null,
        nomor_transaksi varchar(255) not null unique,
        processed_by_full_name varchar(255) not null,
        processed_by_username varchar(255) not null,
        produk varchar(255),
        tipe varchar(255) not null check (tipe in ('DEPOSIT','WITHDRAWAL','TRANSFER')),
        primary key (id)
    );

    create table user_roles (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table users (
        approved boolean not null,
        enabled boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        nim varchar(50),
        username varchar(50) not null unique,
        prodi varchar(100),
        dosen_pembimbing varchar(255),
        email varchar(255) not null,
        full_name varchar(255) not null,
        password varchar(255) not null,
        primary key (id)
    );

    create index idx_transaksi_group_id 
       on transaksi (group_id);

    create index idx_transaksi_nomor 
       on transaksi (nomor_transaksi);

    create index idx_transaksi_rekening 
       on transaksi (nomor_rekening);

    alter table if exists rekening 
       add constraint FKabnl0gddbicgv9nf47vkbl6g5 
       foreign key (nasabah_id) 
       references nasabah;

    alter table if exists transaksi 
       add constraint FK6pvh62gtiktesin1ddf00f3qw 
       foreign key (rekening_id) 
       references rekening;

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
       foreign key (user_id) 
       references users;
